#!bin/bash

echo "" >> ~/.bashrc
echo "#Geoff aliases" >> ~/.bashrc
echo "alias listservice='sudo service --status-all'" >> ~/.bashrc
echo "alias c='clear ; source ~/mybash/welcome'" >> ~/.bashrc
echo "alias s='source ~/mybash/nav'" >> ~/.bashrc
echo "alias showchmod=\"stat --format '%a'\"" >> ~/.bashrc
echo "alias src='source ~/.bashrc'" >> ~/.bashrc
source ~/.bashrc
